"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Services", [
      {
        name: "Flower Maintenance",
        description: "Regular care and maintenance of flower beds and plants.",
        price: 150.0,
        total_orders: 0,
        total_providers: 0,
        category: "gardener",
        image: "uploads/GardenerService/FlowerMaintenance.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Garden Cleaning",
        description: "Complete garden cleaning and waste removal services.",
        price: 180.0,
        total_orders: 0,
        total_providers: 0,
        category: "gardener",
        image: "uploads/GardenerService/GardenCleaning.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Garden Design",
        description: "Creative and custom garden design services.",
        price: 300.0,
        total_orders: 0,
        total_providers: 0,
        category: "gardener",
        image: "uploads/GardenerService/GardenDesign.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Garden Fencing",
        description: "Installation and repair of garden fences.",
        price: 250.0,
        total_orders: 0,
        total_providers: 0,
        category: "gardener",
        image: "uploads/GardenerService/GardenFencing.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Garden Maintenance",
        description: "Ongoing maintenance and seasonal care for gardens.",
        price: 220.0,
        total_orders: 0,
        total_providers: 0,
        category: "gardener",
        image: "uploads/GardenerService/GardenMaintenance.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Garden Pruning",
        description: "Tree and shrub pruning for healthy growth.",
        price: 130.0,
        total_orders: 0,
        total_providers: 0,
        category: "gardener",
        image: "uploads/GardenerService/GardenPruning.png",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Garden Weeding",
        description: "Efficient weeding services for clean garden beds.",
        price: 100.0,
        total_orders: 0,
        total_providers: 0,
        category: "gardener",
        image: "uploads/GardenerService/GardenWeeding.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Pest Maintenance",
        description: "Garden pest inspection and eco-friendly treatment.",
        price: 160.0,
        total_orders: 0,
        total_providers: 0,
        category: "gardener",
        image: "uploads/GardenerService/PestMaintenance.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Plantation Maintenance",
        description: "Maintenance services for indoor and outdoor plantation.",
        price: 190.0,
        total_orders: 0,
        total_providers: 0,
        category: "gardener",
        image: "uploads/GardenerService/PlantationMaintenance.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Snow Clearance",
        description: "Snow removal from gardens and pathways.",
        price: 250.0,
        total_orders: 0,
        total_providers: 0,
        category: "gardener",
        image: "uploads/GardenerService/SnowClearance.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Services", { category: "gardener" }, {});
  },
};
