"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Services", [
      {
        name: "Electric Geyser Installation",
        description:
          "Installation of electric geysers with proper safety measures.",
        price: 300.0,
        total_orders: 0,
        total_providers: 0,
        category: "geyser",
        image: "uploads/GeyserService/ElectricGeyserInstallation.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Electric Heater Installation",
        description: "Professional electric heater installation service.",
        price: 280.0,
        total_orders: 0,
        total_providers: 0,
        category: "geyser",
        image: "uploads/GeyserService/ElectricHeaterInstallation.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Electric Stove Installation",
        description: "Installation of electric stoves by expert technicians.",
        price: 320.0,
        total_orders: 0,
        total_providers: 0,
        category: "geyser",
        image: "uploads/GeyserService/ElectricStoveInstallation.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Gas Heater Installation",
        description: "Safe and efficient installation of gas heaters.",
        price: 350.0,
        total_orders: 0,
        total_providers: 0,
        category: "geyser",
        image: "uploads/GeyserService/GasHeaterInstallation.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Gas Geyser Installation",
        description: "Installation of gas geysers with complete fittings.",
        price: 340.0,
        total_orders: 0,
        total_providers: 0,
        category: "geyser",
        image: "uploads/GeyserService/GasrGeyserInstallation.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Geyser Fitting",
        description: "Mounting and plumbing fittings for new geysers.",
        price: 150.0,
        total_orders: 0,
        total_providers: 0,
        category: "geyser",
        image: "uploads/GeyserService/GeyserFitting.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Geyser Repair",
        description: "Repair services for faulty or leaking geysers.",
        price: 200.0,
        total_orders: 0,
        total_providers: 0,
        category: "geyser",
        image: "uploads/GeyserService/GeyserRepair.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Heater Installation",
        description:
          "Complete heater installation including wiring and safety checks.",
        price: 250.0,
        total_orders: 0,
        total_providers: 0,
        category: "geyser",
        image: "uploads/GeyserService/HeaterInstallation.jpeg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Instant Geyser Installation",
        description: "Quick setup for instant water heating systems.",
        price: 270.0,
        total_orders: 0,
        total_providers: 0,
        category: "geyser",
        image: "uploads/GeyserService/InstantGeyserInstallation.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Solar Geyser Installation",
        description: "Environment-friendly solar geyser system installation.",
        price: 600.0,
        total_orders: 0,
        total_providers: 0,
        category: "geyser",
        image: "uploads/GeyserService/SolarGeyserInstallation.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Services", { category: "geyser" }, {});
  },
};
