"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Services", [
      {
        name: "Bedroom Design",
        description: "Custom bedroom designs tailored to your space.",
        price: 500.0,
        total_orders: 0,
        total_providers: 0,
        category: "carpenter",
        image: "uploads/CarpenterService/BedroomDesign.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Cabinet Design",
        description: "Modern and space-saving cabinet solutions.",
        price: 400.0,
        total_orders: 0,
        total_providers: 0,
        category: "carpenter",
        image: "uploads/CarpenterService/CabinetDesign.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Custom Furniture Design",
        description: "Bespoke furniture built to your vision.",
        price: 600.0,
        total_orders: 0,
        total_providers: 0,
        category: "carpenter",
        image: "uploads/CarpenterService/CustomFurnitureDesign.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Door Fitting",
        description: "Professional door fitting and installation services.",
        price: 150.0,
        total_orders: 0,
        total_providers: 0,
        category: "carpenter",
        image: "uploads/CarpenterService/DoorFitting.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Furniture Repair",
        description: "Restore your old or damaged furniture.",
        price: 200.0,
        total_orders: 0,
        total_providers: 0,
        category: "carpenter",
        image: "uploads/CarpenterService/FurnitureRepair.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Furniture Service",
        description: "General carpentry and furniture maintenance services.",
        price: 180.0,
        total_orders: 0,
        total_providers: 0,
        category: "carpenter",
        image: "uploads/CarpenterService/FurnitureService.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Interior Design Service",
        description: "Complete interior carpentry design and execution.",
        price: 1000.0,
        total_orders: 0,
        total_providers: 0,
        category: "carpenter",
        image: "uploads/CarpenterService/InteriorDesignService.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Wardrobe Design",
        description: "Customized wardrobe layout and build.",
        price: 450.0,
        total_orders: 0,
        total_providers: 0,
        category: "carpenter",
        image: "uploads/CarpenterService/WardrobeDesign.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Window Replacement",
        description: "Window repair and replacement services.",
        price: 220.0,
        total_orders: 0,
        total_providers: 0,
        category: "carpenter",
        image: "uploads/CarpenterService/WindowReplacement.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Wood Work Service",
        description: "All types of custom woodwork services.",
        price: 300.0,
        total_orders: 0,
        total_providers: 0,
        category: "carpenter",
        image: "uploads/CarpenterService/WoodWorkService.jpg",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Services", { category: "carpenter" }, {});
  },
};
